export const HTTP_ERRORS = {
    ENV_VARS_NOT_SET: "ENV_VARS_NOT_SET",
    NOT_FOUND: "NOT_FOUND",
    UNKNOWN_ORIGIN: "BAD_REQUEST",
    COULD_NOT_FETCH_FROM_SUPABASE: "COULD_NOT_FETCH_FROM_SUPABASE",
    ORIGIN_NOT_SET: "BAD_REQUEST",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
  };
  