import { TokenItem } from "../../../utils";

export const DEFAULT_TOKENS_LIST: TokenItem[] = [
  {
    address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    decimals: 6,
    balance: 0.0,
    uiAmount: 0.0,
    chainId: "solana",
    name: "USDC",
    symbol: "USDC",
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png",
    priceUsd: 0.0,
    valueUsd: 0.0,
  } as TokenItem,
  {
    address: "",
    decimals: 9,
    balance: 0.45,
    uiAmount: 151.23,
    chainId: "solana",
    name: "Solana",
    symbol: "SOL",
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png",
    priceUsd: 0.0,
    valueUsd: 807.07,
  } as TokenItem,
  {
    address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    decimals: 6,
    balance: 10000,
    uiAmount: 0.0,
    chainId: "solana",
    name: "USDT",
    symbol: "USDT",
    logoURI: "https://raw.githubusercontent.com/Smaler1/coin/main/logo.png",
    priceUsd: 0.9999,
    valueUsd: 9999.98,
  } as TokenItem,
  {
    address: "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
    decimals: 9,
    balance: 667,
    uiAmount: 0.0,
    chainId: "solana",
    name: "POPCAT",
    symbol: "POPCAT",
    logoURI: "https://popcatsol.com/img/logo.png",
    priceUsd: 1.21,
    valueUsd: 807.07,
  } as TokenItem,
  {
    address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    decimals: 5,
    balance: 1400000,
    uiAmount: 1400000,
    chainId: "solana",
    name: "Bonk",
    symbol: "BONK",
    logoURI: "https://assets.coingecko.com/coins/images/28600/standard/bonk.jpg?1696527587",
    priceUsd: 0.00002074,
    valueUsd: 29.036,
  } as TokenItem,
];
